### PR TITLE
Migrate FP Open `FP2.mk` to `device.mk`

### PR DESCRIPTION
**Pull request by Roboe**
## Description
Add, sort, classify and comment each property and related files from the [`FP2.mk`](https://github.com/FairphoneMirrors/android_device_fairphone_fp2/blob/FP2-open-16.10.0/FP2.mk) (FP Open 16.10.0)

## Other things done in the while:
- Update blobs list to those of FP Open 16.10.0
- Add initial ramdisk (to be improved by #1)

## Status
- Build passing: yes
- `dt.img` stills quite light, 217088 bytes (FP Open one is 4646912 bytes) 
- `boot.img`: expected to not boot (incomplete or not signed; because of `dt.img`, probably)
- `recovery.img`: not tested yet
- `boot.img`: not tested yet

## How to try to build
Modify `.repo/local_manifest/fp2.xml` like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="Roboe/android_device_fairphone_fp2" path="device/fairphone/fp2" remote="github" revision="cm-12.1" />
  <project name="WeAreFairphone/android_kernel_fairphone_fp2" path="kernel/fairphone/fp2" remote="github" revision="cm-12.1" />
</manifest>
```

Run in your environment:
```
repo sync --force-sync
source build/envsetup.sh
breakfast m8d # should sync same cm.dependencies
brunch fp2
```

### CODE REVIEW

**Comment by z3ntu** [comment]
I somehow can't get past the error

> target thumb C++: libstagefright <= frameworks/av/media/libstagefright/StagefrightMetadataRetriever.cpp
target thumb C++: libstagefright <= frameworks/av/media/libstagefright/SurfaceMediaSource.cpp
target thumb C++: libstagefright <= frameworks/av/media/libstagefright/ThrottledSource.cpp
target thumb C++: libstagefright <= frameworks/av/media/libstagefright/TimeSource.cpp
target thumb C++: libstagefright <= frameworks/av/media/libstagefright/TimedEventQueue.cpp
target thumb C++: libstagefright <= frameworks/av/media/libstagefright/Utils.cpp
frameworks/av/media/libstagefright/Utils.cpp:45:24: fatal error: audio_defs.h: No such file or directory
 #include "audio_defs.h"
                        ^
compilation terminated.
make: *** [/var/android/out/target/product/fp2/obj/SHARED_LIBRARIES/libstagefright_intermediates/Utils.o] Error 1

**Comment by Roboe** [comment]
I'll let a clean overnight build running. Let's see if I can reproduce that

**Comment by Roboe** [comment]
Yes, build stopped just at that exact error:
```
frameworks/av/media/libstagefright/Utils.cpp:45:24: fatal error: audio_defs.h: No such file or directory
 #include "audio_defs.h"
```

There's an `audio_defs.h` file at `hardware/qcom/audio-caf/msm8974/hal/audio_extn/audio_defs.h`
(on the FP Open source, based on CAF, it is located at `hardware/qcom/audio/hal/audio_extn/audio_defs.h`)

Let's see how we can include that file...

**Comment by Arvil** [comment]
Hi, I don't understand the need for `breakfast m8d` that relies on a foreign configuration when we can add the pertinent repositories to the local manifest (keeping them in cm.dependencies in hope that FP2 will be added to CM's official repos seems fine though).

**Comment by Arvil** [comment]
Hi, just a quick addition, I just made a fresh build from scratch, my `device/fairphone/fp2` repo is at [e77c25b](https://github.com/WeAreFairphone/android_device_fairphone_fp2/pull/2/commits/e77c25bcb31561cb78dd8330417738eebea9aa0d) (plus my own modifications from #1 ) and I have the same error as you. Funnily enough I could build without a single problem before.

**Comment by Arvil** [comment]
From frameworks/av/media/libstagefright/Utils.cpp:41 :

```
#ifdef ENABLE_AV_ENHANCEMENTS
#include "QCMediaDefs.h"
#include "QCMetaData.h"
#ifndef QCOM_DIRECTTRACK
#include "audio_defs.h"
#endif
#endif
```

So the line

```
# Media
TARGET_ENABLE_QC_AV_ENHANCEMENTS := true
```

in BoardConfig.mk is clearly at fault here. I'll attempt a build without it and report  accordingly.

**Comment by Roboe** [comment]
Syncing deps with a local manifest is another way to achieve the same purpose, but it conflicts on my side with a previously test build of `m8d`. I think that can be solved with a `<remove-project>` tag or similar, but I don't feel like investigating that, :sweat_smile:

**Comment by Roboe** [comment]
There's [no other device](https://github.com/search?q=org%3ACyanogenMod+ENABLE_AV_ENHANCEMENTS&type=Code) with `ENABLE_AV_ENHANCEMENT` in BoardConfig.mk, so I will delete that and try a build.

**Comment by Arvil** [comment]
> What about QCOM_DIRECTTRACK? 

I've seen a post on cyanogenmod reviews about how this was deprecated for a while. Will try to find it again.
 
> But, anyway, why is the compiler not finding an audio_defs.h, if there's is one at hardware/qcom/audio-caf/msm8974/hal/audio_extn/audio_defs.h?

Includes are searched for in the out/ directory where header files are copied at the beginning of the build. If we don't use audio-caf these header files are not copied

**Comment by Arvil** [comment]
Unless anyone thinks it's a bad idea, I propose we merge this alongside arvil/android_device_fairphone_fp2@a869800e11fe5671eca8ff7ab3b8b24fa597552d that makes allows `Utils.cpp` to build.

**Pull request merged**
